version: "3.9"

services:
  python_app:
    container_name: python_app
    image: therapeutics_1
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_URL=postgresql+psycopg2://postgres:postgres@postgres_db:5432/postgres   
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres  

